### ISSUE TITLE
Dialog title / description spacing too large

### ISSUE THREAD

**Issue by wbobeirne** [IroncladDev/FediModBoilerplate#1]
Fedi app

![CleanShot 2023-11-13 at 17 10 45@2x](https://github.com/IroncladDev/FediModBoilerplate/assets/649992/622656d4-8230-4eac-8c6c-30896d149201)

Boilerplate

![CleanShot 2023-11-13 at 17 10 51@2x](https://github.com/IroncladDev/FediModBoilerplate/assets/649992/f0db8c23-ef91-4c7e-b319-7554781caca9)

**Comment by IroncladDev** [comment]
Fixed in https://github.com/IroncladDev/FediModBoilerplate/commit/012c710cc089dc75fae7df998face9f3eb39f3de
